import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Intro from "@/components/Intro";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='scroll-smooth'>
        <Header />
        <main className='w-full animate-intro-ascend-content opacity-0'>{children}</main>
        <Intro />
      </body>
    </html>
  );
}
